### ISSUE TITLE
Select out a few good threads from groups

### ISSUE THREAD

**Issue by seongyher** [thephilosophersmeme/thephilosophersmeme#8]

**Comment by seongyher** [comment]
Leave a [B]omment

**Comment by 74yearoldsocialist** [comment]
test [B]ost

**Comment by jcahill** [comment]
| Group  | Thread Topic & Permalink                                              | OP                   |
|--------|-----------------------------------------------------------------------|----------------------|
| /tpmg/ | [Memes as supernormal stimuli](https://facebook.com/1566820800006441) | Zakhail Conrad Nacua |

**Comment by jcahill** [comment]
closed and wontfix: seems there are no good tpm threads
